name: py312_keras_torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - imbalanced-learn=0.14.0=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - libblas=3.11.0=4_hf2e6a31_mkl
  - libcblas=3.11.0=4_h2a3cdd5_mkl
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=4_hf9ab0e9_mkl
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.7=h4fa8253_0
  - mkl=2025.3.0=hac47afa_454
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyhc872135_0
  - python=3.12.12=h716150d_1
  - python_abi=3.12=3_cp312
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.12.0
      - h5py==3.15.1
      - imageio==2.37.2
      - intel-cmplr-lib-ur==2025.3.1
      - intel-openmp==2025.3.1
      - jinja2==3.1.6
      - keras==3.12.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.6.1
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - optree==0.18.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rich==14.2.0
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.14.0
      - tcmlib==1.4.1
      - tifffile==2025.10.16
      - torch==2.10.0.dev20251211+cu130
      - torchaudio==2.10.0.dev20251211+cu130
      - torchvision==0.25.0.dev20251211+cu130
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - umf==1.0.2
prefix: C:\Users\garz8\.conda\envs\py312_keras_torch
